name: Flutter Web
on:
  push:
    branches:
      - main
permissions: 
  contents: write
jobs:
  build:
    name: Build Web
#     env:
#       my_secret: $ {{ secrets.COMMIT_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - run: |
          git config --global user.email ikinye86@gmail.com
          git config --global user.name rollcake86
      - uses: erickzanardo/flutter-gh-pages@v3
#         with:
#           channel: 'stable'
#       - run: flutter config --enable-web
#       - run: flutter pub get
#       - run: flutter build web --release
#         # 1. change path which exist lib/main.dart
#         working-directory: ./webtest
#       - run: |
#           # 2. change path to [existed lib/main.dart path]/build/web
#           cd ./webTest/build/web
#           git init
#            # 3. change your email
#           git config --global user.email ikinye86@gmail.com
#           # 4. change your name
#           git config --global user.name rollcake86
#           git status
#           # 5. change your repository
#           git remote add origin https://$@github.com/rollcake86/webtest.git
#           git add --all
#           git commit -m "update"
#           git push origin main
